var format_HHDensity = new ol.format.GeoJSON();
var features_HHDensity = format_HHDensity.readFeatures(geojson_HHDensity, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_HHDensity = new ol.source.Vector();
jsonSource_HHDensity.addFeatures(features_HHDensity);var lyr_HHDensity = new ol.layer.Vector({
                source:jsonSource_HHDensity, 
                style: style_HHDensity,
                title: "HH Density"
            });var format_Walka = new ol.format.GeoJSON();
var features_Walka = format_Walka.readFeatures(geojson_Walka, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Walka = new ol.source.Vector();
jsonSource_Walka.addFeatures(features_Walka);var lyr_Walka = new ol.layer.Vector({
                source:jsonSource_Walka, 
                style: style_Walka,
                title: "Walka"
            });var format_Std = new ol.format.GeoJSON();
var features_Std = format_Std.readFeatures(geojson_Std, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Std = new ol.source.Vector();
jsonSource_Std.addFeatures(features_Std);var lyr_Std = new ol.layer.Vector({
                source:jsonSource_Std, 
                style: style_Std,
                title: "Std"
            });var format_OpenSpaceDummy = new ol.format.GeoJSON();
var features_OpenSpaceDummy = format_OpenSpaceDummy.readFeatures(geojson_OpenSpaceDummy, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_OpenSpaceDummy = new ol.source.Vector();
jsonSource_OpenSpaceDummy.addFeatures(features_OpenSpaceDummy);var lyr_OpenSpaceDummy = new ol.layer.Vector({
                source:jsonSource_OpenSpaceDummy, 
                style: style_OpenSpaceDummy,
                title: "Open Space (Dummy)"
            });var format_OpenSpaceRatio = new ol.format.GeoJSON();
var features_OpenSpaceRatio = format_OpenSpaceRatio.readFeatures(geojson_OpenSpaceRatio, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_OpenSpaceRatio = new ol.source.Vector();
jsonSource_OpenSpaceRatio.addFeatures(features_OpenSpaceRatio);var lyr_OpenSpaceRatio = new ol.layer.Vector({
                source:jsonSource_OpenSpaceRatio, 
                style: style_OpenSpaceRatio,
                title: "Open Space (Ratio)"
            });var format_Density = new ol.format.GeoJSON();
var features_Density = format_Density.readFeatures(geojson_Density, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Density = new ol.source.Vector();
jsonSource_Density.addFeatures(features_Density);var lyr_Density = new ol.layer.Vector({
                source:jsonSource_Density, 
                style: style_Density,
                title: "Density"
            });var format_MixedUse = new ol.format.GeoJSON();
var features_MixedUse = format_MixedUse.readFeatures(geojson_MixedUse, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MixedUse = new ol.source.Vector();
jsonSource_MixedUse.addFeatures(features_MixedUse);var lyr_MixedUse = new ol.layer.Vector({
                source:jsonSource_MixedUse, 
                style: style_MixedUse,
                title: "Mixed Use"
            });var format_AfricanAmerican = new ol.format.GeoJSON();
var features_AfricanAmerican = format_AfricanAmerican.readFeatures(geojson_AfricanAmerican, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_AfricanAmerican = new ol.source.Vector();
jsonSource_AfricanAmerican.addFeatures(features_AfricanAmerican);var lyr_AfricanAmerican = new ol.layer.Vector({
                source:jsonSource_AfricanAmerican, 
                style: style_AfricanAmerican,
                title: "African American"
            });var format_CES30Score = new ol.format.GeoJSON();
var features_CES30Score = format_CES30Score.readFeatures(geojson_CES30Score, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CES30Score = new ol.source.Vector();
jsonSource_CES30Score.addFeatures(features_CES30Score);var lyr_CES30Score = new ol.layer.Vector({
                source:jsonSource_CES30Score, 
                style: style_CES30Score,
                title: "CES 3.0 Score"
            });var format_Traffic = new ol.format.GeoJSON();
var features_Traffic = format_Traffic.readFeatures(geojson_Traffic, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Traffic = new ol.source.Vector();
jsonSource_Traffic.addFeatures(features_Traffic);var lyr_Traffic = new ol.layer.Vector({
                source:jsonSource_Traffic, 
                style: style_Traffic,
                title: "Traffic"
            });var format_PovertyRate = new ol.format.GeoJSON();
var features_PovertyRate = format_PovertyRate.readFeatures(geojson_PovertyRate, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_PovertyRate = new ol.source.Vector();
jsonSource_PovertyRate.addFeatures(features_PovertyRate);var lyr_PovertyRate = new ol.layer.Vector({
                source:jsonSource_PovertyRate, 
                style: style_PovertyRate,
                title: "Poverty Rate"
            });var format_PollutionBurdenScore = new ol.format.GeoJSON();
var features_PollutionBurdenScore = format_PollutionBurdenScore.readFeatures(geojson_PollutionBurdenScore, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_PollutionBurdenScore = new ol.source.Vector();
jsonSource_PollutionBurdenScore.addFeatures(features_PollutionBurdenScore);var lyr_PollutionBurdenScore = new ol.layer.Vector({
                source:jsonSource_PollutionBurdenScore, 
                style: style_PollutionBurdenScore,
                title: "Pollution Burden Score"
            });var format_HospitalVisitsAsthma = new ol.format.GeoJSON();
var features_HospitalVisitsAsthma = format_HospitalVisitsAsthma.readFeatures(geojson_HospitalVisitsAsthma, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_HospitalVisitsAsthma = new ol.source.Vector();
jsonSource_HospitalVisitsAsthma.addFeatures(features_HospitalVisitsAsthma);var lyr_HospitalVisitsAsthma = new ol.layer.Vector({
                source:jsonSource_HospitalVisitsAsthma, 
                style: style_HospitalVisitsAsthma,
                title: "Hospital Visits (Asthma)"
            });var format_CensusTract = new ol.format.GeoJSON();
var features_CensusTract = format_CensusTract.readFeatures(geojson_CensusTract, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CensusTract = new ol.source.Vector();
jsonSource_CensusTract.addFeatures(features_CensusTract);var lyr_CensusTract = new ol.layer.Vector({
                source:jsonSource_CensusTract, 
                style: style_CensusTract,
                title: "Census Tract"
            });var format_MajorArterials = new ol.format.GeoJSON();
var features_MajorArterials = format_MajorArterials.readFeatures(geojson_MajorArterials, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_MajorArterials = new ol.source.Vector();
jsonSource_MajorArterials.addFeatures(features_MajorArterials);var lyr_MajorArterials = new ol.layer.Vector({
                source:jsonSource_MajorArterials, 
                style: style_MajorArterials,
                title: "Major Arterials"
            });var format_County = new ol.format.GeoJSON();
var features_County = format_County.readFeatures(geojson_County, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_County = new ol.source.Vector();
jsonSource_County.addFeatures(features_County);var lyr_County = new ol.layer.Vector({
                source:jsonSource_County, 
                style: style_County,
                title: "County"
            });

lyr_HHDensity.setVisible(true);lyr_Walka.setVisible(true);lyr_Std.setVisible(true);lyr_OpenSpaceDummy.setVisible(true);lyr_OpenSpaceRatio.setVisible(true);lyr_Density.setVisible(true);lyr_MixedUse.setVisible(true);lyr_AfricanAmerican.setVisible(true);lyr_CES30Score.setVisible(true);lyr_Traffic.setVisible(true);lyr_PovertyRate.setVisible(true);lyr_PollutionBurdenScore.setVisible(true);lyr_HospitalVisitsAsthma.setVisible(true);lyr_CensusTract.setVisible(true);lyr_MajorArterials.setVisible(true);lyr_County.setVisible(true);
var layersList = [lyr_HHDensity,lyr_Walka,lyr_Std,lyr_OpenSpaceDummy,lyr_OpenSpaceRatio,lyr_Density,lyr_MixedUse,lyr_AfricanAmerican,lyr_CES30Score,lyr_Traffic,lyr_PovertyRate,lyr_PollutionBurdenScore,lyr_HospitalVisitsAsthma,lyr_CensusTract,lyr_MajorArterials,lyr_County];
lyr_HHDensity.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_Walka.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_Std.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_OpenSpaceDummy.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_OpenSpaceRatio.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_Density.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_MixedUse.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'fid': 'fid', 'statefp10': 'statefp10', 'countyfp10': 'countyfp10', 'tractce10': 'tractce10', 'name10': 'name10', 'namelsad10': 'namelsad10', 'acres': 'acres', 'dst_fwy12': 'dst_fwy12', 'dst_fwy40': 'dst_fwy40', 'dst_hqtc12': 'dst_hqtc12', 'dst_hqtc40': 'dst_hqtc40', 'dst_rail12': 'dst_rail12', 'rail12_mod': 'rail12_mod', 'dst_rail40': 'dst_rail40', 'rail40_mod': 'rail40_mod', 'dens': 'dens', 'pc': 'pc', 'phis': 'phis', 'nemp': 'nemp', 'landsm': 'landsm', 'empden': 'empden', 'walka': 'walka', 'std': 'std', 'hhden': 'hhden', 'lum': 'lum', 'luma': 'luma', 'povertyn': 'povertyn', 'areasum': 'areasum', 'osum': 'osum', 'oratio': 'oratio', 'odummy': 'odummy', });
lyr_AfricanAmerican.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_CES30Score.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_Traffic.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_PovertyRate.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_PollutionBurdenScore.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_HospitalVisitsAsthma.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', 'did': 'did', 'tpop': 'tpop', 'calcnty': 'calcnty', 'zip': 'zip', 'city': 'city', 'lon': 'lon', 'lat': 'lat', 'cesscore0': 'cesscore0', 'cespctl': 'cespctl', 'o3': 'o3', 'o3pctl': 'o3pctl', 'pm250': 'pm250', 'pm25pctl': 'pm25pctl', 'pmdsl': 'pmdsl', 'pmdslpctl': 'pmdslpctl', 'dwater0': 'dwater0', 'dwaterpctl': 'dwaterpctl', 'pest': 'pest', 'pestpctl': 'pestpctl', 'tox': 'tox', 'toxpctl': 'toxpctl', 'trafficn0': 'trafficn0', 'trafficpct': 'trafficpct', 'cleansite': 'cleansite', 'cleansitep': 'cleansitep', 'gwthreat': 'gwthreat', 'gwthreatpc': 'gwthreatpc', 'hazwaste': 'hazwaste', 'hazwastepc': 'hazwastepc', 'iwb': 'iwb', 'iwbpctl': 'iwbpctl', 'solidwaste': 'solidwaste', 'solidwas_1': 'solidwas_1', 'pburden': 'pburden', 'pburdensco': 'pburdensco', 'pburdenpct': 'pburdenpct', 'asthma': 'asthma', 'asthmapctl': 'asthmapctl', 'lbw0': 'lbw0', 'lbw0pctl': 'lbw0pctl', 'cardio': 'cardio', 'caridopctl': 'caridopctl', 'edu0': 'edu0', 'edu0pctl': 'edu0pctl', 'lang0': 'lang0', 'lang0pctl': 'lang0pctl', 'pov0': 'pov0', 'pov0pctl': 'pov0pctl', 'unemp0': 'unemp0', 'unemp0pctl': 'unemp0pctl', 'raincome0': 'raincome0', 'raincome0p': 'raincome0p', 'popchar0': 'popchar0', 'popchars0': 'popchars0', 'popchar0pc': 'popchar0pc', 'cespctlr': 'cespctlr', 'calcnty2': 'calcnty2', 'pop10': 'pop10', 'pop1164': 'pop1164', 'pop65': 'pop65', 'white0': 'white0', 'black0': 'black0', 'native0': 'native0', 'asian0': 'asian0', 'other0': 'other0', 'cesscore': 'cesscore', 'pm25': 'pm25', 'dwater': 'dwater', 'trafficn': 'trafficn', 'edu': 'edu', 'lang': 'lang', 'pov': 'pov', 'unemp': 'unemp', 'raincome': 'raincome', 'popchar': 'popchar', 'popchars': 'popchars', 'lbw': 'lbw', 'white': 'white', 'black': 'black', 'native': 'native', 'asian': 'asian', 'other': 'other', 'county': 'county', });
lyr_CensusTract.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'TRACTCE': 'TRACTCE', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'MTFCC': 'MTFCC', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', });
lyr_MajorArterials.set('fieldAliases', {'LINEARID': 'LINEARID', 'FULLNAME': 'FULLNAME', 'RTTYP': 'RTTYP', 'MTFCC': 'MTFCC', });
lyr_County.set('fieldAliases', {'STATEFP': 'STATEFP', 'COUNTYFP': 'COUNTYFP', 'COUNTYNS': 'COUNTYNS', 'GEOID': 'GEOID', 'NAME': 'NAME', 'NAMELSAD': 'NAMELSAD', 'LSAD': 'LSAD', 'CLASSFP': 'CLASSFP', 'MTFCC': 'MTFCC', 'CSAFP': 'CSAFP', 'CBSAFP': 'CBSAFP', 'METDIVFP': 'METDIVFP', 'FUNCSTAT': 'FUNCSTAT', 'ALAND': 'ALAND', 'AWATER': 'AWATER', 'INTPTLAT': 'INTPTLAT', 'INTPTLON': 'INTPTLON', });
lyr_HHDensity.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_Walka.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_Std.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_OpenSpaceDummy.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_OpenSpaceRatio.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_Density.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_MixedUse.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'fid': 'TextEdit', 'statefp10': 'TextEdit', 'countyfp10': 'TextEdit', 'tractce10': 'TextEdit', 'name10': 'TextEdit', 'namelsad10': 'TextEdit', 'acres': 'TextEdit', 'dst_fwy12': 'TextEdit', 'dst_fwy40': 'TextEdit', 'dst_hqtc12': 'TextEdit', 'dst_hqtc40': 'TextEdit', 'dst_rail12': 'TextEdit', 'rail12_mod': 'TextEdit', 'dst_rail40': 'TextEdit', 'rail40_mod': 'TextEdit', 'dens': 'TextEdit', 'pc': 'TextEdit', 'phis': 'TextEdit', 'nemp': 'TextEdit', 'landsm': 'TextEdit', 'empden': 'TextEdit', 'walka': 'TextEdit', 'std': 'TextEdit', 'hhden': 'TextEdit', 'lum': 'TextEdit', 'luma': 'TextEdit', 'povertyn': 'TextEdit', 'areasum': 'TextEdit', 'osum': 'TextEdit', 'oratio': 'TextEdit', 'odummy': 'TextEdit', });
lyr_AfricanAmerican.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_CES30Score.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_Traffic.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_PovertyRate.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_PollutionBurdenScore.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_HospitalVisitsAsthma.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', 'did': 'TextEdit', 'tpop': 'TextEdit', 'calcnty': 'TextEdit', 'zip': 'TextEdit', 'city': 'TextEdit', 'lon': 'TextEdit', 'lat': 'TextEdit', 'cesscore0': 'TextEdit', 'cespctl': 'TextEdit', 'o3': 'TextEdit', 'o3pctl': 'TextEdit', 'pm250': 'TextEdit', 'pm25pctl': 'TextEdit', 'pmdsl': 'TextEdit', 'pmdslpctl': 'TextEdit', 'dwater0': 'TextEdit', 'dwaterpctl': 'TextEdit', 'pest': 'TextEdit', 'pestpctl': 'TextEdit', 'tox': 'TextEdit', 'toxpctl': 'TextEdit', 'trafficn0': 'TextEdit', 'trafficpct': 'TextEdit', 'cleansite': 'TextEdit', 'cleansitep': 'TextEdit', 'gwthreat': 'TextEdit', 'gwthreatpc': 'TextEdit', 'hazwaste': 'TextEdit', 'hazwastepc': 'TextEdit', 'iwb': 'TextEdit', 'iwbpctl': 'TextEdit', 'solidwaste': 'TextEdit', 'solidwas_1': 'TextEdit', 'pburden': 'TextEdit', 'pburdensco': 'TextEdit', 'pburdenpct': 'TextEdit', 'asthma': 'TextEdit', 'asthmapctl': 'TextEdit', 'lbw0': 'TextEdit', 'lbw0pctl': 'TextEdit', 'cardio': 'TextEdit', 'caridopctl': 'TextEdit', 'edu0': 'TextEdit', 'edu0pctl': 'TextEdit', 'lang0': 'TextEdit', 'lang0pctl': 'TextEdit', 'pov0': 'TextEdit', 'pov0pctl': 'TextEdit', 'unemp0': 'TextEdit', 'unemp0pctl': 'TextEdit', 'raincome0': 'TextEdit', 'raincome0p': 'TextEdit', 'popchar0': 'TextEdit', 'popchars0': 'TextEdit', 'popchar0pc': 'TextEdit', 'cespctlr': 'TextEdit', 'calcnty2': 'TextEdit', 'pop10': 'TextEdit', 'pop1164': 'TextEdit', 'pop65': 'TextEdit', 'white0': 'TextEdit', 'black0': 'TextEdit', 'native0': 'TextEdit', 'asian0': 'TextEdit', 'other0': 'TextEdit', 'cesscore': 'TextEdit', 'pm25': 'TextEdit', 'dwater': 'TextEdit', 'trafficn': 'TextEdit', 'edu': 'TextEdit', 'lang': 'TextEdit', 'pov': 'TextEdit', 'unemp': 'TextEdit', 'raincome': 'TextEdit', 'popchar': 'TextEdit', 'popchars': 'TextEdit', 'lbw': 'TextEdit', 'white': 'TextEdit', 'black': 'TextEdit', 'native': 'TextEdit', 'asian': 'TextEdit', 'other': 'TextEdit', 'county': 'TextEdit', });
lyr_CensusTract.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'TRACTCE': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'MTFCC': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', });
lyr_MajorArterials.set('fieldImages', {'LINEARID': 'TextEdit', 'FULLNAME': 'TextEdit', 'RTTYP': 'TextEdit', 'MTFCC': 'TextEdit', });
lyr_County.set('fieldImages', {'STATEFP': 'TextEdit', 'COUNTYFP': 'TextEdit', 'COUNTYNS': 'TextEdit', 'GEOID': 'TextEdit', 'NAME': 'TextEdit', 'NAMELSAD': 'TextEdit', 'LSAD': 'TextEdit', 'CLASSFP': 'TextEdit', 'MTFCC': 'TextEdit', 'CSAFP': 'TextEdit', 'CBSAFP': 'TextEdit', 'METDIVFP': 'TextEdit', 'FUNCSTAT': 'TextEdit', 'ALAND': 'TextEdit', 'AWATER': 'TextEdit', 'INTPTLAT': 'TextEdit', 'INTPTLON': 'TextEdit', });
lyr_HHDensity.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_Walka.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_Std.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_OpenSpaceDummy.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_OpenSpaceRatio.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_Density.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_MixedUse.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'fid': 'no label', 'statefp10': 'no label', 'countyfp10': 'no label', 'tractce10': 'no label', 'name10': 'no label', 'namelsad10': 'no label', 'acres': 'no label', 'dst_fwy12': 'no label', 'dst_fwy40': 'no label', 'dst_hqtc12': 'no label', 'dst_hqtc40': 'no label', 'dst_rail12': 'no label', 'rail12_mod': 'no label', 'dst_rail40': 'no label', 'rail40_mod': 'no label', 'dens': 'no label', 'pc': 'no label', 'phis': 'no label', 'nemp': 'no label', 'landsm': 'no label', 'empden': 'no label', 'walka': 'no label', 'std': 'no label', 'hhden': 'no label', 'lum': 'no label', 'luma': 'no label', 'povertyn': 'no label', 'areasum': 'no label', 'osum': 'no label', 'oratio': 'no label', 'odummy': 'no label', });
lyr_AfricanAmerican.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'no label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_CES30Score.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'no label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_Traffic.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'no label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_PovertyRate.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'no label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_PollutionBurdenScore.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'no label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_HospitalVisitsAsthma.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', 'did': 'no label', 'tpop': 'no label', 'calcnty': 'no label', 'zip': 'no label', 'city': 'no label', 'lon': 'no label', 'lat': 'no label', 'cesscore0': 'no label', 'cespctl': 'no label', 'o3': 'no label', 'o3pctl': 'no label', 'pm250': 'no label', 'pm25pctl': 'no label', 'pmdsl': 'no label', 'pmdslpctl': 'no label', 'dwater0': 'no label', 'dwaterpctl': 'no label', 'pest': 'no label', 'pestpctl': 'no label', 'tox': 'no label', 'toxpctl': 'no label', 'trafficn0': 'no label', 'trafficpct': 'no label', 'cleansite': 'no label', 'cleansitep': 'no label', 'gwthreat': 'no label', 'gwthreatpc': 'no label', 'hazwaste': 'no label', 'hazwastepc': 'no label', 'iwb': 'no label', 'iwbpctl': 'no label', 'solidwaste': 'no label', 'solidwas_1': 'no label', 'pburden': 'no label', 'pburdensco': 'no label', 'pburdenpct': 'no label', 'asthma': 'inline label', 'asthmapctl': 'no label', 'lbw0': 'no label', 'lbw0pctl': 'no label', 'cardio': 'no label', 'caridopctl': 'no label', 'edu0': 'no label', 'edu0pctl': 'no label', 'lang0': 'no label', 'lang0pctl': 'no label', 'pov0': 'no label', 'pov0pctl': 'no label', 'unemp0': 'no label', 'unemp0pctl': 'no label', 'raincome0': 'no label', 'raincome0p': 'no label', 'popchar0': 'no label', 'popchars0': 'no label', 'popchar0pc': 'no label', 'cespctlr': 'no label', 'calcnty2': 'no label', 'pop10': 'no label', 'pop1164': 'no label', 'pop65': 'no label', 'white0': 'no label', 'black0': 'no label', 'native0': 'no label', 'asian0': 'no label', 'other0': 'no label', 'cesscore': 'no label', 'pm25': 'no label', 'dwater': 'no label', 'trafficn': 'no label', 'edu': 'no label', 'lang': 'no label', 'pov': 'no label', 'unemp': 'no label', 'raincome': 'no label', 'popchar': 'no label', 'popchars': 'no label', 'lbw': 'no label', 'white': 'no label', 'black': 'no label', 'native': 'no label', 'asian': 'no label', 'other': 'no label', 'county': 'no label', });
lyr_CensusTract.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'TRACTCE': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'MTFCC': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', });
lyr_MajorArterials.set('fieldLabels', {'LINEARID': 'no label', 'FULLNAME': 'no label', 'RTTYP': 'no label', 'MTFCC': 'no label', });
lyr_County.set('fieldLabels', {'STATEFP': 'no label', 'COUNTYFP': 'no label', 'COUNTYNS': 'no label', 'GEOID': 'no label', 'NAME': 'no label', 'NAMELSAD': 'no label', 'LSAD': 'no label', 'CLASSFP': 'no label', 'MTFCC': 'no label', 'CSAFP': 'no label', 'CBSAFP': 'no label', 'METDIVFP': 'no label', 'FUNCSTAT': 'no label', 'ALAND': 'no label', 'AWATER': 'no label', 'INTPTLAT': 'no label', 'INTPTLON': 'no label', });
lyr_County.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});